### ISSUE TITLE
Add units for property size and price

### ISSUE THREAD

**Issue by MrEarle** [PHPeople-UC/backend#11]
Que `size` y `price` sean un objeto de la forma:

```js
{ value: 1000, unit: "UF"}
```

Esto agrega mas flexibilidad para distintos ordenes de magnitud en propiedades (chicas y grandes)

**Comment by jerosalazar** [comment]
Es necesario que price tenga unidad también? Podríamos tomarlo todo solamente como CLP a menos que quieran ponerle soporte para otras monedas

**Comment by MrEarle** [comment]
En Chile ya tenemos UF. Pero puede ser que esté bien dejar todo en UF.

El tamaño sí necesita unidad. Puede ser en M2 o en hectareas

**Comment by rhanuch** [comment]
le voy a asignar un `enum` a los tamaños de las propiedades y diria que seria mejor dejar todo en UF
