### ISSUE TITLE
Agregar owner a property

### ISSUE THREAD

**Issue by MrEarle** [PHPeople-UC/backend#9]
Incluir el owner (al menos su nombre) en una property

**Comment by jerosalazar** [comment]
El model de properties tiene la relación de user. Con esto hacemos la referencia a owner, está bien con eso o quieren que la api entregue la referencia con el nombre "owner" en vez de "user"?

**Comment by MrEarle** [comment]
Da lo mismo si es owner o user. Necesitamos que se incluya en las properties al hacer el get

**Comment by jerosalazar** [comment]
Perfect, entonces ya está implementada. Revisando me di cuenta que lo que nos faltaba era devolverlo en el serializer de property así que lo agrego altok
